import type {
  Incident, Shelter, Alert, Volunteer, SOSRequest,
  DashboardStats, ActivityItem, ChartDataPoint, TimeSeriesPoint,
} from "@/types";

// ============================================
// Dashboard Statistics
// ============================================
export const mockDashboardStats: DashboardStats = {
  activeIncidents: 23,
  totalShelters: 147,
  deployedVolunteers: 1284,
  activeAlerts: 8,
  totalEvacuated: 45200,
  responseTimeAvg: "4.2 min",
  resourceUtilization: 78,
  pendingRequests: 34,
};

// ============================================
// Incidents
// ============================================
export const mockIncidents: Incident[] = [
  {
    id: "INC-2024-001",
    title: "Category 4 Hurricane — Gulf Coast",
    description: "Hurricane Elena making landfall along the Gulf Coast with sustained winds of 140mph. Major flooding expected in low-lying areas.",
    type: "hurricane",
    severity: "critical",
    status: "active",
    location: { lat: 29.7604, lng: -95.3698 },
    address: "Houston Metropolitan Area, TX",
    reportedBy: "NWS Houston",
    assignedTo: "Federal Response Team Alpha",
    affectedPopulation: 250000,
    deployedResources: 450,
    createdAt: "2024-03-15T08:30:00Z",
    updatedAt: "2024-03-15T14:22:00Z",
  },
  {
    id: "INC-2024-002",
    title: "7.2 Magnitude Earthquake — Pacific Northwest",
    description: "Major seismic event detected along the Cascadia subduction zone. Multiple structural collapses reported in urban areas.",
    type: "earthquake",
    severity: "critical",
    status: "active",
    location: { lat: 47.6062, lng: -122.3321 },
    address: "Seattle Metropolitan Area, WA",
    reportedBy: "USGS Seismic Network",
    assignedTo: "Federal Response Team Bravo",
    affectedPopulation: 180000,
    deployedResources: 320,
    createdAt: "2024-03-14T03:15:00Z",
    updatedAt: "2024-03-15T11:45:00Z",
  },
  {
    id: "INC-2024-003",
    title: "Wildfire Complex — Sierra Nevada",
    description: "Multi-fire complex spanning 45,000 acres. Mandatory evacuations in effect for 12 communities.",
    type: "fire",
    severity: "high",
    status: "active",
    location: { lat: 37.8651, lng: -119.5383 },
    address: "Yosemite Region, CA",
    reportedBy: "CAL FIRE",
    assignedTo: "Wildfire Response Unit Delta",
    affectedPopulation: 35000,
    deployedResources: 280,
    createdAt: "2024-03-12T16:00:00Z",
    updatedAt: "2024-03-15T09:30:00Z",
  },
  {
    id: "INC-2024-004",
    title: "Flash Flooding — Appalachian Region",
    description: "Heavy rainfall causing flash flooding across multiple counties. Several roads impassable.",
    type: "flood",
    severity: "medium",
    status: "monitoring",
    location: { lat: 36.1627, lng: -86.7816 },
    address: "Nashville Area, TN",
    reportedBy: "Local Emergency Management",
    affectedPopulation: 12000,
    deployedResources: 85,
    createdAt: "2024-03-15T05:00:00Z",
    updatedAt: "2024-03-15T13:00:00Z",
  },
  {
    id: "INC-2024-005",
    title: "Chemical Spill — Industrial Complex",
    description: "Hazardous material release at petrochemical facility. 2-mile evacuation zone established.",
    type: "chemical",
    severity: "high",
    status: "pending",
    location: { lat: 30.0664, lng: -93.7321 },
    address: "Lake Charles Industrial Corridor, LA",
    reportedBy: "EPA Rapid Response",
    affectedPopulation: 8500,
    deployedResources: 120,
    createdAt: "2024-03-15T10:15:00Z",
    updatedAt: "2024-03-15T12:30:00Z",
  },
  {
    id: "INC-2024-006",
    title: "Tornado Outbreak — Great Plains",
    description: "Multiple tornadoes confirmed across Kansas and Oklahoma. EF3+ storms reported.",
    type: "tornado",
    severity: "high",
    status: "resolved",
    location: { lat: 35.4676, lng: -97.5164 },
    address: "Oklahoma City Metro, OK",
    reportedBy: "NWS Norman",
    affectedPopulation: 45000,
    deployedResources: 200,
    createdAt: "2024-03-13T18:00:00Z",
    updatedAt: "2024-03-14T22:00:00Z",
    resolvedAt: "2024-03-14T22:00:00Z",
  },
];

// ============================================
// Shelters
// ============================================
export const mockShelters: Shelter[] = [
  {
    id: "SH-001",
    name: "Houston Convention Center",
    address: "1001 Avenida De Las Americas, Houston, TX 77010",
    location: { lat: 29.7520, lng: -95.3561 },
    capacity: 10000,
    currentOccupancy: 7845,
    status: "open",
    amenities: ["Medical", "Food", "Water", "Charging", "Pet-Friendly", "ADA Accessible"],
    contact: "(713) 555-0100",
    operatingHours: "24/7 Emergency Operations",
    lastUpdated: "2024-03-15T14:00:00Z",
  },
  {
    id: "SH-002",
    name: "Tacoma Dome Emergency Shelter",
    address: "2727 E D St, Tacoma, WA 98421",
    location: { lat: 47.2361, lng: -122.4278 },
    capacity: 5000,
    currentOccupancy: 4200,
    status: "open",
    amenities: ["Medical", "Food", "Water", "Showers", "ADA Accessible"],
    contact: "(253) 555-0200",
    operatingHours: "24/7 Emergency Operations",
    lastUpdated: "2024-03-15T13:30:00Z",
  },
  {
    id: "SH-003",
    name: "Fresno Fairgrounds Relief Center",
    address: "1121 S Chance Ave, Fresno, CA 93702",
    location: { lat: 36.7253, lng: -119.7521 },
    capacity: 3000,
    currentOccupancy: 2890,
    status: "full",
    amenities: ["Medical", "Food", "Water", "Pet-Friendly"],
    contact: "(559) 555-0300",
    operatingHours: "24/7 Emergency Operations",
    lastUpdated: "2024-03-15T12:00:00Z",
  },
  {
    id: "SH-004",
    name: "Nashville Community Center",
    address: "862 4th Ave S, Nashville, TN 37210",
    location: { lat: 36.1512, lng: -86.7762 },
    capacity: 2000,
    currentOccupancy: 850,
    status: "open",
    amenities: ["Food", "Water", "Charging", "ADA Accessible"],
    contact: "(615) 555-0400",
    operatingHours: "06:00 - 22:00",
    lastUpdated: "2024-03-15T11:00:00Z",
  },
  {
    id: "SH-005",
    name: "Portland Emergency Hub",
    address: "777 NE MLK Jr Blvd, Portland, OR 97232",
    location: { lat: 45.5289, lng: -122.6617 },
    capacity: 4000,
    currentOccupancy: 0,
    status: "closed",
    amenities: ["Medical", "Food", "Water", "Showers", "Pet-Friendly", "ADA Accessible"],
    contact: "(503) 555-0500",
    operatingHours: "Closed — Awaiting Activation",
    lastUpdated: "2024-03-15T10:00:00Z",
  },
];

// ============================================
// Alerts
// ============================================
export const mockAlerts: Alert[] = [
  {
    id: "ALT-001",
    title: "Hurricane Elena — Extreme Danger",
    message: "Category 4 Hurricane Elena expected to make landfall within 6 hours. All residents in evacuation zones A-D must evacuate immediately. Do not delay.",
    severity: "critical",
    status: "active",
    affectedAreas: ["Houston", "Galveston", "Beaumont", "Port Arthur"],
    issuedBy: "National Weather Service",
    issuedAt: "2024-03-15T08:00:00Z",
    expiresAt: "2024-03-16T08:00:00Z",
    broadcastChannels: ["EAS", "WEA", "NOAA Radio", "Social Media"],
  },
  {
    id: "ALT-002",
    title: "Earthquake Aftershock Warning",
    message: "Significant aftershocks (M5.0+) expected in the next 72 hours following the M7.2 event. Avoid damaged structures. Check gas lines.",
    severity: "warning",
    status: "active",
    affectedAreas: ["Seattle", "Tacoma", "Olympia", "Bellevue"],
    issuedBy: "USGS",
    issuedAt: "2024-03-14T04:00:00Z",
    expiresAt: "2024-03-17T04:00:00Z",
    broadcastChannels: ["EAS", "WEA", "Social Media"],
  },
  {
    id: "ALT-003",
    title: "Air Quality Advisory — Wildfire Smoke",
    message: "Air quality index exceeds 200 (Very Unhealthy) due to wildfire smoke. Limit outdoor activities. Vulnerable populations should remain indoors.",
    severity: "warning",
    status: "active",
    affectedAreas: ["Fresno", "Madera", "Merced", "Yosemite Valley"],
    issuedBy: "EPA / AirNow",
    issuedAt: "2024-03-13T12:00:00Z",
    expiresAt: "2024-03-16T12:00:00Z",
    broadcastChannels: ["Social Media", "Local News"],
  },
  {
    id: "ALT-004",
    title: "Chemical Evacuation Order",
    message: "Mandatory evacuation within a 2-mile radius of the Lake Charles Industrial Complex. Shelter-in-place for residents 2-5 miles out.",
    severity: "critical",
    status: "active",
    affectedAreas: ["Lake Charles", "Westlake", "Sulphur"],
    issuedBy: "EPA Rapid Response",
    issuedAt: "2024-03-15T10:30:00Z",
    expiresAt: "2024-03-15T22:00:00Z",
    broadcastChannels: ["EAS", "WEA", "Emergency Sirens", "Door-to-Door"],
  },
  {
    id: "ALT-005",
    title: "Flash Flood Watch Expired",
    message: "The flash flood watch for the Nashville metropolitan area has been allowed to expire. Continue to monitor local conditions.",
    severity: "info",
    status: "expired",
    affectedAreas: ["Nashville", "Davidson County"],
    issuedBy: "NWS Nashville",
    issuedAt: "2024-03-15T06:00:00Z",
    expiresAt: "2024-03-15T12:00:00Z",
    broadcastChannels: ["NOAA Radio"],
  },
];

// ============================================
// Volunteers
// ============================================
export const mockVolunteers: Volunteer[] = [
  {
    id: "VOL-001",
    name: "Dr. Sarah Chen",
    email: "s.chen@disasterlink.org",
    phone: "(206) 555-0101",
    status: "deployed",
    specialty: "medical",
    certifications: ["EMT-P", "CERT", "HAZMAT Awareness"],
    deployedTo: "INC-2024-002",
    sector: "Alpha-7",
    hoursLogged: 342,
    missionsCompleted: 28,
    rating: 4.9,
    lastActive: "2024-03-15T14:00:00Z",
  },
  {
    id: "VOL-002",
    name: "Marcus Rivera",
    email: "m.rivera@disasterlink.org",
    phone: "(713) 555-0102",
    status: "deployed",
    specialty: "search-rescue",
    certifications: ["USAR Level II", "Swift Water Rescue", "Rope Rescue"],
    deployedTo: "INC-2024-001",
    sector: "Bravo-3",
    hoursLogged: 567,
    missionsCompleted: 45,
    rating: 4.8,
    lastActive: "2024-03-15T13:45:00Z",
  },
  {
    id: "VOL-003",
    name: "Priya Sharma",
    email: "p.sharma@disasterlink.org",
    phone: "(559) 555-0103",
    status: "available",
    specialty: "logistics",
    certifications: ["ICS-200", "Supply Chain Management", "CDL Class A"],
    hoursLogged: 210,
    missionsCompleted: 15,
    rating: 4.7,
    lastActive: "2024-03-15T10:00:00Z",
  },
  {
    id: "VOL-004",
    name: "James Washington",
    email: "j.washington@disasterlink.org",
    phone: "(615) 555-0104",
    status: "standby",
    specialty: "communications",
    certifications: ["HAM Radio License", "Satellite Comms", "ICS-300"],
    hoursLogged: 128,
    missionsCompleted: 9,
    rating: 4.6,
    lastActive: "2024-03-15T08:00:00Z",
  },
  {
    id: "VOL-005",
    name: "Emily Tanaka",
    email: "e.tanaka@disasterlink.org",
    phone: "(503) 555-0105",
    status: "off-duty",
    specialty: "shelter-ops",
    certifications: ["Red Cross Shelter Manager", "First Aid", "CNA"],
    hoursLogged: 445,
    missionsCompleted: 32,
    rating: 4.9,
    lastActive: "2024-03-14T22:00:00Z",
  },
  {
    id: "VOL-006",
    name: "Carlos Mendez",
    email: "c.mendez@disasterlink.org",
    phone: "(210) 555-0106",
    status: "deployed",
    specialty: "transport",
    certifications: ["CDL Class B", "Forklift Certified", "HAZMAT Transport"],
    deployedTo: "INC-2024-001",
    sector: "Charlie-1",
    hoursLogged: 389,
    missionsCompleted: 22,
    rating: 4.5,
    lastActive: "2024-03-15T14:15:00Z",
  },
];

// ============================================
// SOS Requests
// ============================================
export const mockSOSRequests: SOSRequest[] = [
  {
    id: "SOS-001",
    type: "rescue",
    status: "in-progress",
    description: "Family of 4 trapped on second floor of flooded home. Water rising. Need immediate boat rescue.",
    location: { lat: 29.7820, lng: -95.3803 },
    address: "2345 Heights Blvd, Houston, TX 77008",
    requestedBy: "Maria Gonzalez",
    requestedAt: "2024-03-15T11:30:00Z",
    respondedAt: "2024-03-15T11:35:00Z",
    assignedTeam: "Swift Water Rescue Team 3",
    priority: "critical",
    peopleAffected: 4,
  },
  {
    id: "SOS-002",
    type: "medical",
    status: "pending",
    description: "Elderly couple, both diabetic, running low on insulin. Need medical supplies and potential evacuation.",
    location: { lat: 29.7250, lng: -95.4000 },
    address: "789 Westheimer Rd, Houston, TX 77006",
    requestedBy: "Robert Kim",
    requestedAt: "2024-03-15T12:45:00Z",
    priority: "high",
    peopleAffected: 2,
  },
  {
    id: "SOS-003",
    type: "shelter",
    status: "acknowledged",
    description: "Group of 15 displaced from apartment complex. Need shelter assignment and transportation.",
    location: { lat: 29.7500, lng: -95.3600 },
    address: "1200 Main St, Houston, TX 77002",
    requestedBy: "Ahmed Hassan",
    requestedAt: "2024-03-15T13:00:00Z",
    respondedAt: "2024-03-15T13:05:00Z",
    priority: "medium",
    peopleAffected: 15,
  },
  {
    id: "SOS-004",
    type: "supplies",
    status: "resolved",
    description: "Community center sheltering 50 people needs water, blankets, and baby formula.",
    location: { lat: 29.6800, lng: -95.4100 },
    address: "456 South Main, Houston, TX 77025",
    requestedBy: "Pastor Williams",
    requestedAt: "2024-03-15T09:00:00Z",
    respondedAt: "2024-03-15T09:15:00Z",
    resolvedAt: "2024-03-15T10:30:00Z",
    assignedTeam: "Logistics Unit 7",
    priority: "medium",
    peopleAffected: 50,
  },
];

// ============================================
// Activity Feed
// ============================================
export const mockActivityFeed: ActivityItem[] = [
  {
    id: "ACT-001",
    type: "incident_created",
    title: "New Incident Reported",
    description: "Category 4 Hurricane Elena — Gulf Coast. Critical severity. 250,000 potentially affected.",
    timestamp: "2024-03-15T14:22:00Z",
    actor: "NWS Houston",
  },
  {
    id: "ACT-002",
    type: "volunteer_deployed",
    title: "Volunteer Team Deployed",
    description: "Swift Water Rescue Team 3 deployed to SOS-001 (Heights Blvd rescue).",
    timestamp: "2024-03-15T14:15:00Z",
    actor: "Operations Command",
  },
  {
    id: "ACT-003",
    type: "alert_issued",
    title: "Emergency Alert Broadcast",
    description: "Chemical Evacuation Order issued for Lake Charles area via EAS, WEA, and Emergency Sirens.",
    timestamp: "2024-03-15T14:00:00Z",
    actor: "EPA Rapid Response",
  },
  {
    id: "ACT-004",
    type: "shelter_opened",
    title: "Shelter Capacity Update",
    description: "Houston Convention Center at 78% capacity (7,845 / 10,000). Additional wings being opened.",
    timestamp: "2024-03-15T13:45:00Z",
    actor: "Shelter Operations",
  },
  {
    id: "ACT-005",
    type: "sos_received",
    title: "SOS Request Received",
    description: "Medical emergency — Elderly couple needs insulin and potential evacuation at 789 Westheimer Rd.",
    timestamp: "2024-03-15T13:30:00Z",
    actor: "Citizen Portal",
  },
  {
    id: "ACT-006",
    type: "resource_dispatched",
    title: "Resources Dispatched",
    description: "3 medical supply trucks and 2 ambulances dispatched to Galveston staging area.",
    timestamp: "2024-03-15T13:15:00Z",
    actor: "Logistics Command",
  },
  {
    id: "ACT-007",
    type: "incident_resolved",
    title: "Incident Resolved",
    description: "Tornado Outbreak — Great Plains (INC-2024-006) marked as resolved. All-clear issued.",
    timestamp: "2024-03-14T22:00:00Z",
    actor: "NWS Norman",
  },
];

// ============================================
// Chart Data
// ============================================
export const incidentsByType: ChartDataPoint[] = [
  { name: "Hurricane", value: 3 },
  { name: "Earthquake", value: 5 },
  { name: "Wildfire", value: 8 },
  { name: "Flood", value: 12 },
  { name: "Tornado", value: 6 },
  { name: "Chemical", value: 2 },
  { name: "Other", value: 4 },
];

export const responseTimeTrend: TimeSeriesPoint[] = [
  { date: "Jan", value: 8.2 },
  { date: "Feb", value: 7.5 },
  { date: "Mar", value: 6.8 },
  { date: "Apr", value: 5.9 },
  { date: "May", value: 5.2 },
  { date: "Jun", value: 4.8 },
  { date: "Jul", value: 4.5 },
  { date: "Aug", value: 4.2 },
  { date: "Sep", value: 4.0 },
  { date: "Oct", value: 3.8 },
  { date: "Nov", value: 3.5 },
  { date: "Dec", value: 3.2 },
];

export const volunteerDeployment: ChartDataPoint[] = [
  { name: "Medical", value: 280 },
  { name: "Search & Rescue", value: 340 },
  { name: "Logistics", value: 220 },
  { name: "Communications", value: 120 },
  { name: "Shelter Ops", value: 180 },
  { name: "Transport", value: 144 },
];

export const shelterUtilization: ChartDataPoint[] = [
  { name: "Houston CC", value: 78 },
  { name: "Tacoma Dome", value: 84 },
  { name: "Fresno Fair", value: 96 },
  { name: "Nashville CC", value: 42 },
  { name: "Portland Hub", value: 0 },
];

export const monthlyIncidents: TimeSeriesPoint[] = [
  { date: "Jan", value: 12 },
  { date: "Feb", value: 8 },
  { date: "Mar", value: 15 },
  { date: "Apr", value: 22 },
  { date: "May", value: 18 },
  { date: "Jun", value: 28 },
  { date: "Jul", value: 35 },
  { date: "Aug", value: 42 },
  { date: "Sep", value: 38 },
  { date: "Oct", value: 25 },
  { date: "Nov", value: 15 },
  { date: "Dec", value: 10 },
];

export const resourceAllocation: ChartDataPoint[] = [
  { name: "Personnel", value: 45 },
  { name: "Vehicles", value: 20 },
  { name: "Medical Supplies", value: 15 },
  { name: "Food & Water", value: 12 },
  { name: "Equipment", value: 8 },
];
